package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildStep
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        step {
            name = "test-scan"
            id = "test_scan"
            type = "sonar-plugin"
            param("sonarServer", "9efd98dd-ab58-4702-a30a-f19a35036558")
        }
    }
    steps {
        update<BuildStep>(0) {
            clearConditions()
            param("sonarProjectSources", ".")
            param("sonarProjectName", "React")
            param("sonarProjectKey", "React")
            param("sonarProjectVersion", "")
        }
    }
}
