name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout React App
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: echo "npm ci"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Copy kube config file
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
            mkdir .kube
            echo "${{ env.KUBECONFIG }}" >> .kube/config
            curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
            kubectl get nodes