name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout React App
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: echo "npm ci"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Docker Tag
        id: docker_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_SHA} | cut -c1-7)"       

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}:${{ steps.docker_tag.outputs.tag }}

      - name: Set Output
        id: vars
        run: echo "::set-output name=tag::${{ steps.docker_tag.outputs.tag }}"        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clone K8s Manifests Repo
      run: |
        git clone https://x-access-token:${{ secrets.MANIFEST_REPO_PAT }}@github.com/${{ secrets.K8S_MANIFEST_REPO }}.git k8s-manifests
        cd k8s-manifests
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: List Repository Contents
      run: |
        cd k8s-manifests
        ls -la
        git branch -a

    - name: Update Kubernetes Manifests
      env:
        DOCKER_TAG: ${{ needs.build.outputs.docker_tag }} 
      run: |
        cd k8s-manifests/k8s
        sed -i 's|image: ${{ secrets.DOCKER_IMAGE }}:.*|image: ${{ secrets.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}|' k8s/app.yml
        git add .
        git commit -m "Update image tag to ${{ env.DOCKER_TAG }}"
        git push