name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        echo "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        echo "docker build -t yourusername/yourapp:${{ github.sha }} ."
        echo "docker push yourusername/yourapp:${{ github.sha }}"